# Generated by Django 6.0.3 on 2026-03-11 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('base_url', models.URLField(max_length=500)),
                ('credentials', models.JSONField(help_text='{"username": "...", "password": "..."}')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),

                # db_index=True — register_beat_schedules() in tasks.py queries
                # BookingSystem.objects.filter(is_active=True) at every startup.
                # This index makes that filter instant regardless of how many
                # booking systems exist.
                ('is_active', models.BooleanField(db_index=True, default=True)),

                # db_index=True — sync status endpoint and admin filtering by
                # sync state hits this column. Small table now but important
                # as the number of connected booking systems grows over time.
                ('sync_status', models.CharField(
                    choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('error', 'Error')],
                    db_index=True,
                    default='pending',
                    max_length=20,
                )),
                ('last_sync_error', models.TextField(blank=True, default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),

                # db_index=True — during sync every upsert looks up by external_id
                # to decide create vs update. Without this index, each sync
                # operation scans the entire customers table — catastrophic on
                # large datasets syncing every 6 hours.
                ('external_id', models.CharField(db_index=True, max_length=100)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('booking_system', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='customers',
                    to='appointment_app.bookingsystem',
                )),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),

                # db_index=True — same reasoning as Customer.external_id above.
                # Every provider upsert during sync lookups by external_id first.
                ('external_id', models.CharField(db_index=True, max_length=100)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('booking_system', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='providers',
                    to='appointment_app.bookingsystem',
                )),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('duration_minutes', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='BDT', max_length=10)),

                # db_index=True — same reasoning as Customer/Provider external_id.
                # Sync upserts look up services by external_id to avoid duplicates.
                ('external_id', models.CharField(db_index=True, max_length=100)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('booking_system', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='services',
                    to='appointment_app.bookingsystem',
                )),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),

                # db_index=True — single-column fallback index for queries that
                # do not filter by booking_system first, such as admin queries,
                # cross-system date range scans, or future endpoints that query
                # appointments globally by date.
                ('start_time', models.DateTimeField(db_index=True)),
                ('end_time', models.DateTimeField()),

                # db_index=True — filtering appointments by status (Booked,
                # Cancelled, Completed) is used by dashboard views showing only
                # active bookings and cancellation rate reports. Without this,
                # status filtering requires a full table scan.
                ('status', models.CharField(
                    choices=[('Booked', 'Booked'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed')],
                    db_index=True,
                    default='Booked',
                    max_length=20,
                )),
                ('location', models.CharField(blank=True, default='', max_length=255)),

                # db_index=True — every appointment upsert during sync looks up
                # by external_id. Without this index, each sync scans the entire
                # appointments table — the most expensive table in the system.
                ('external_id', models.CharField(db_index=True, max_length=100)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('booking_system', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='appointments',
                    to='appointment_app.bookingsystem',
                )),
                ('customer', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='appointments',
                    to='appointment_app.customer',
                )),
                ('provider', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='appointments',
                    to='appointment_app.provider',
                )),
                ('service', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='appointments',
                    to='appointment_app.service',
                )),
            ],
        ),

        # ----------------------------------------------------------------------
        # INDEX: customer(booking_system, last_name, first_name)
        #
        # Scopes customer lookups to a booking system and covers name-based
        # searches and sorting in a single index scan. The name fields are
        # included so ORDER BY last_name, first_name resolves from the index
        # without touching the heap (index-only scan for name queries).
        # ----------------------------------------------------------------------
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(
                fields=['booking_system', 'last_name', 'first_name'],
                name='appointment_booking_12629c_idx',
            ),
        ),

        # unique_together → (booking_system, external_id) on Customer
        # Not just data integrity — PostgreSQL automatically creates a unique
        # B-tree index for this constraint. Upsert lookups during sync use
        # this index, making each lookup O(log n) instead of O(n).
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('booking_system', 'external_id')},
        ),

        # ----------------------------------------------------------------------
        # INDEX: provider(booking_system, last_name, first_name)
        #
        # Speeds up provider name lookups and search filtering scoped to a
        # booking system. The name fields are included so the index covers
        # ORDER BY and search queries on provider names without touching the
        # heap — same pattern as the customer index above.
        # ----------------------------------------------------------------------
        migrations.AddIndex(
            model_name='provider',
            index=models.Index(
                fields=['booking_system', 'last_name', 'first_name'],
                name='appointment_booking_2d07dd_idx',
            ),
        ),

        # unique_together → (booking_system, external_id) on Provider
        # Implicitly creates a unique B-tree index. Sync upserts use this
        # to check for existing providers before create/update decisions.
        migrations.AlterUniqueTogether(
            name='provider',
            unique_together={('booking_system', 'external_id')},
        ),

        # ----------------------------------------------------------------------
        # INDEX: service(booking_system, name)
        #
        # Service lookups are always scoped to a booking system. Including
        # name makes this a covering index for service search queries —
        # WHERE booking_system_id = X AND name ILIKE '%haircut%' resolves
        # entirely from the index without touching the heap.
        # ----------------------------------------------------------------------
        migrations.AddIndex(
            model_name='service',
            index=models.Index(
                fields=['booking_system', 'name'],
                name='appointment_booking_3711a6_idx',
            ),
        ),

        # unique_together → (booking_system, external_id) on Service
        # Implicitly creates a unique B-tree index used by sync upserts.
        migrations.AlterUniqueTogether(
            name='service',
            unique_together={('booking_system', 'external_id')},
        ),

        # ----------------------------------------------------------------------
        # INDEX: appointment(booking_system, start_time)
        #
        # The most important index. Every analytics query filters by
        # booking_system_id first, then date-ranges on start_time. The
        # composite order matters — equality filter (booking_system) goes
        # first to partition the scan, then start_time for the range.
        # Without this, every report query does a full table scan across
        # all booking systems.
        # ----------------------------------------------------------------------
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(
                fields=['booking_system', 'start_time'],
                name='appointment_booking_c039c1_idx',
            ),
        ),

        # ----------------------------------------------------------------------
        # INDEX: appointment(booking_system, provider, start_time)
        #
        # Optimizes the top-providers aggregation query specifically. When
        # grouping appointments by provider within a booking system over a
        # date range, PostgreSQL uses this index to resolve the WHERE +
        # GROUP BY in one pass instead of scanning all appointments and
        # then sorting. Without this: hash aggregate over a full filtered scan.
        # ----------------------------------------------------------------------
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(
                fields=['booking_system', 'provider', 'start_time'],
                name='appointment_booking_0b6455_idx',
            ),
        ),

        # ----------------------------------------------------------------------
        # INDEX: appointment(booking_system, service, start_time)
        #
        # Same reasoning as the provider index above but for the top-services
        # aggregation. Grouping by service within a booking system over a
        # date range hits this index directly. Without it, the GROUP BY
        # service requires a hash aggregate over a full filtered scan.
        # ----------------------------------------------------------------------
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(
                fields=['booking_system', 'service', 'start_time'],
                name='appointment_booking_25c3b8_idx',
            ),
        ),

        # unique_together → (booking_system, external_id) on Appointment
        # Implicitly creates a unique B-tree index. The most critical upsert
        # index — appointments are the largest table and sync runs every 6h.
        # Without this index every sync would scan millions of rows.
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('booking_system', 'external_id')},
        ),
    ]