# Generated by Django 6.0.3 on 2026-03-11 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment_app.service'),
        ),
        migrations.AlterField(
            model_name='bookingsystem',
            name='credentials',
            field=models.JSONField(),
        ),
    ]
